name: Update YARA rules

on:
  schedule:
    - cron: '0 0 * * 1' # At 00:00 on Monday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.2' # install the python version needed

#      - name: install python packages
#        run: |
#          python -m pip install --upgrade pip
#          pip install -r requirements.txt

      - name: execute py script
        run: python download_yara_rules.py

# Progress: https://www.python-engineer.com/posts/run-python-github-actions/#use-secrets-api-tokens-in-github-actions